- ModularTegustation/tegu_items/disciplinary/research.dm
The CRA breacher now sends the abnormality to a random Xenospawn.
CRAs in general would dogpile the abnormality when it breaches. 
That's not really how we want to showcase these abnormalities. Now instead it moves to a Xenospawn.
:cl:
balance: CRA breacher now moves the abnormality to a random xenospawn.
/:cl:
> CRA Breacher now sends the abnormality to a random xenospawn.

- code/modules/mob/living/simple_animal/abnormality/he/shock_centipede.dm
Did you know Shock Centipede is missing work result visual overlays? No? You don't take it? Well, it's been bothering me for months.
Why was it missing them? Someone did an override on the SuccessEffect, NeutralEffect and FailureEffect but forgot to call the parent proc.
Bugfix
:cl:
fix: Fixes Shock Centipede work result overlays
/:cl:
> Readds visual work result overlays to Shock Centipede

- code/modules/mob/living/simple_animal/hostile/ordeal/indigo/dusk.dm
Fix: Will no longer target dead bodies with trash disposal.
Balance: Heals less per hit on CoL.
Tweak: Staff can now change how much it regens per life tick and on hit while empowered.
Bugfix is good. Also might be a little evil for CoL.
:cl:
balance: Red Commander healing nerf on CoL
fix: Trash Disposal no longer targets bodies
/:cl:
> Indigo Dusk Red Commander bugfix and minor healing nerf

- code/__DEFINES/attributes.dm
- code/__DEFINES/mobs.dm
- code/controllers/subsystem/maptype.dm
- code/datums/attributes/_attribute.dm
- code/datums/attributes/fortitude.dm
- code/datums/attributes/prudence.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_helpers.dm
Refactors health and sanity calculation without actually changing anything player-side. 
Fortitude and Prudence HP/SP modifiers are now baked into the define, with handling for the station trait changing mid-round due to admeme.
Fortitude and Prudence base stats update automatically if it changes mid shift.
"De-shittifies" /mob/living/carbon/human/updatehealth()
Adds `get_attribute_printed_level_bonus()` which is used by updatehealth(); There wasn't a simply way to do this before without redundant looping, and "get_printed_level_bonus()" already does the Health and Sanity math for us.
Code Improvement.
:cl:
add: `get_attribute_printed_level_bonus()`
code: Refactors `FORTITUDE_MOD` and `PRUDENCE_MOD`, defines `DEFAULT_HUMAN_MAX_HEALTH_XP` and `DEFAULT_HUMAN_MAX_SANITY_XP`
/:cl:
> Health Code Refactor

- code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
Violet Midnight damage changes.
Red/Black deal slightly more damage (270/250 up from 220)
Pale Eye deals slightly less damage (30 down from 40)
Violet needed a few minor number changes for it to be a bit more fair, Pale eye could trap you, and Red/Black both needed a tiny bit more oomph to them. 
White was unchanged due to hitting entire departments.
:cl:
balance: Violet Midnight damage has been adjusted.
/:cl:
> Violet Midnight Number Change

- code/modules/clothing/suits/ego_gear/_ego_gear.dm
Armor now takes 7 seconds to equip.
Armor equips instantly near an EGO console or armor fridge.
Holding multiple EGO armor now no longer slows you.
I want to make minor changes to the armor equip system.
This makes you want to equip EGO at extraction, instead of just on the fly.
:cl:
balance: rebalanced equipping EGO
/:cl:
> Armor Equipment Update

- ModularTegustation/tegu_items/associations/skills/liu/associate.dm
- ModularTegustation/tegu_items/associations/skills/liu/director.dm
- ModularTegustation/tegu_items/associations/skills/seven/associate.dm
- ModularTegustation/tegu_items/associations/skills/seven/director.dm
- ModularTegustation/tegu_items/associations/skills/seven/veteran.dm
- ModularTegustation/tegu_items/associations/skills/zwei/director.dm
- code/modules/mob/living/simple_animal/dc_changes.dm
- code/modules/mob/living/simple_animal/hostile/ordeal/brown/dawn.dm
Lust Peccatula were meant to have only a 25% chance to block projectiles, however they did not call their parent proc for projectiles so they just ignored everything, also fixes all Assoc Skill bugs and ties Thermals to Analysis
Seven require Thermals without X-Ray to viably use their smoke in combat, Lust Peccatula being entirely ranged immune is not intended behaviour and bugs are bad.
:cl:
tweak: tweaked "Analysis" Seven skill to give passive Thermals
fix: fixed bugs related to assoc skills
fix: fixed lust peccatula having complete ranged immunity
/:cl:
> Bugfixes Lust Peccatula ranged immunity and bugfixes all known issues with Association skills

- code/__HELPERS/roundend.dm
If it's too early in the round (sub 100 PE generated) or it's not LC13, the facility rank will not show up.
There's no need for it on rounds where it's impossible to get better ranks!
:cl:
fix: Facility Rank no longer shows as D when there's no PE generated
/:cl:
> Facility Rank will no longer show up if you don't have one

- code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
This makes big bird's counter lower by 2 instead of 1 when someone dies. Meaning it takes about only 3 deaths for a breach to occur.
Big bird is a WAW, and while its breach reflects that, it is way too generous in both its work rates and safety net, meaning it will only realistically breach during a meltdown. Big bird will now only need about 3 deaths before it breaches, but considering its counter can be increased on a good work, I think that it can still be handled even during a terrible time for the facility.
:cl:
balance: Big Bird's counter will now drop by 2 on someone's death instead of 1.
/:cl:
> Makes big bird's counter more punishing.

- ModularLobotomy/ego_weapons/ranged/ego_bullets/he.dm
- ModularLobotomy/ego_weapons/ranged/he.dm
ABS was heavily overbuffed.
Here's what this PR does:
- Lowers the damage from 85 > 70
- Increases Reload from 2.1 > 3.5
- Increases Fire Delay from 10 > 15
Ardor Blossom Star was overbuffed. It is supposed to be an AMR rifle, and it is, with piercing, but before it just overshined Magic Bullet. This PR nerfs ABS.
:cl:
balance: rebalanced Ardor Blossom Star
/:cl:
> Nerfs Ardor Blossom Star

- code/modules/paperwork/records/info/tools.dm
Jekyll's info file did not mention that if you return the tool while using it, it instantly insanes you, now it does.
Apart from that, there were slight changes to the info file as a whole that, in my opinion, describe better the functionality of the abnormality.
Clarity is good when its an instakill/instainsane mechanic.
:cl:
tweak: Improved clarity in Jekyll's info file.
/:cl:
> Changes to Jekyll's Records (No more surprise insanity)

- code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
What the title says. It prevents Big Bird chomping midwalk so it should avoid the accidental 2 range.
Less unfair deaths
:cl:
fix: fixed BB range
/:cl:
> Prevents Big Bird from having extra range from him attacking while moving

- code/datums/abnormality/datum/abnormality.dm
- code/modules/events/abno_events/docile.dm
- lobotomy-corp13.dme
Adds an event that makes abnormality produce 75% more PE but make you gain 75% less stats for working them.
The event will not hit the highest threat abnormality if it's alone, just in case it's the only trainer available. The effect lasts for about 6 minutes, and is meant to shake up how easy it is to train on an abno or obtain its ego.
I think events adding more variety to what's optimal to work on at any given moment would be nice, it's an event that can be good or bad depending on the situation, which is what events should be.
:cl:
add: Docile abno event. Abnormalities will produce more PE but give you less stats for working them for the event's duration.
/:cl:
> Docile Abno Event

- code/modules/jobs/job_types/assistant.dm
Replaces one of the two ultra-senior clerks with Assistinator.
It caused bugs when both of the Clerk ultra-seniors used the same outfit.
This changes one of them
:cl:
tweak: Replaced one of the two ultrasenior clerks with assistinator 
/:cl:
> Replaces one of the two Clerks with Assistinator

- code/controllers/subsystem/statpanel.dm
- code/modules/mob/living/carbon/human/human.dm
Now displays Game Speed and Station Trait in the Stat Panel. Station Trait is already an OOC-knowledge thing you can check in our discord, and Game Speed shouldn't be a secret thing, it is literally voted on at round start.
They will only be displayed on Facility modes.
Note: yes this PR edits human.dm, it adds an empty string before displaying intent and movement mode in the stat panel. This is so it doesn't look weird. If I add the empty string in statpanel.dm it will look bad when viewing it as a ghost or in the lobby.
> Examples of how the stat panel looks now:
- Alive as a human:
- Alive as an Abno:
- In the Lobby:
- Observer:
This is information that should be available to everyone. Station Traits are already available in our discord, Gamespeed is something that will be useful to …
> Adds Gamespeed and Station Trait to the Stat Panel

- code/modules/mob/living/simple_animal/abnormality/teth/clayman.dm
- code/modules/paperwork/records/info/teth.dm
When clay is worked, the relevant work type will gain 10% work chance, and the other work types will lose 5% work chance. Should any work type reach a 100%, ALL work types will go back to 20%, however its counter will not lower on failure until at least one work type is at 50%
Clayman is one of those abnormalities that's cooler in its concept and designs than it is in execution. It rarely ever breach, as its work rates are all equally as generous, and as such it also rarely gets to use or abuse its work damage. Its ego is good, yet not outstanding despite the versatile damage type it has. Generic indeed.
This aims to make generic brand modelling clay fill a unique niche within its TETH tier, all while giving it greater opportunities to deal its random damage, making it more than a filler …
> Generic Brand Modelling Clay small rework.

- _maps/Quests/ruined_town.dmm
- code/modules/mob/living/simple_animal/hostile/netherworld.dm
This just reduces the number of hana crates in the Ruined Town Quest to 3 in the migo area, changes the other crates into money crates and buffs the migos to have +50 HP, and deal 3 WHITE damage on hit. (Used to be 1-3 WHITE damage)
Makes that area a bit more challenging, which makes the new prize for beating that area make more sense.
:cl:
balance: ruined town migos
balance: replaced some hana crates with ahn crates in the migo area.
/:cl:
> Minor City Update: Migo buff/Ruined Town nerf

- ModularLobotomy/lc13_obj/lc13_computers/abnormality_auxiliary.dm
- code/controllers/subsystem/lobotomy_corp.dm
- code/controllers/subsystem/ticker.dm
- code/modules/jobs/job_types/manager.dm
- code/modules/ordeals/_ordeal.dm
This PR makes it so the restriction which makes it so that only Managers can start Core Suppressions gets disabled, if there isn't a Manager at certain points in the round.
Default behaviour: Only Manager can start Cores & Extra Cores.
15 minutes into the round, there will be a check for a living Manager. If there isn't one, the restriction is lifted. At that point, anyone can start a Core Suppression.
If a Manager joins after the restriction has been lifted, the restriction will be activated again.
If Extra Cores are unlocked, there will be another check for a Manager, and if there isn't one, the restrictions will be lifted again.
tl;dr: you can do core suppressions without a manager, if one doesn't show up
Makes runs without Managers have the possibility of doing Cores, but Managers …
> Core Suppressions for Manager-less shifts

- code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
Freischütz' fleeing teleport SFX is now louder, displays a visible message, and there's a small VFX when he teleports in/out. If we had a real portal sprite for him I'd have used it, at the moment it's just a recoloured KoD teleport VFX.
Better visual and audio clarity, to avoid "oh, the tall guy with the gun disappeared, I must've killed him"
https://github.com/user-attachments/assets/0889ae9f-ff5f-46fc-9021-ee86c2e87fc7
:cl:
tweak: Freischütz egress has a visible message, SFX was made louder, now has entry/egress VFX
/:cl:
> Freischütz teleport visible message & louder SFX

- ModularLobotomy/associations/skills/liu/associate.dm
- ModularLobotomy/associations/skills/liu/director.dm
- ModularLobotomy/associations/skills/liu/veteran.dm
- code/datums/status_effects/debuffs.dm
- code/game/objects/effects/abnormality.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/life.dm
- code/modules/mob/living/simple_animal/abnormality/he/ardor_blossom_moth.dm
- code/modules/reagents/chemistry/reagents/other_reagents.dm
Fire effects such as those created by Ardor Blossom Moth, God of the Seasons, and Liu are extinguishable now.
Fire status effect has 3 stacks removed when extinguished. This seems to make sense since fire can apply several stacks when you walk onto it or cross several at the same time.
Dark Flame from magic bullet is not extinguishable due to its abnormal nature.
Unsure how it will actually effect gameplay since burn stacks are not reduced additively but instead divided by 2 each tick. So if you get 10 stacks and get extinguished you would have 7 stacks:
10/5/2.5/1.25 vs 7/3.5/1.75
Base ss13 fire now does damage again because it turns out the damage caused by fire in base SS13 is entirely from temperature increase. Ive changed this to be a flat 4 damage when on fire from normal things. …
> Fires are Extinguishable Now [Seems to Work]

- code/controllers/configuration/entries/general.dm
- code/controllers/subsystem/discord.dm
- config/example/config.txt
Adds code that allows pings to be sent via TGS should `HIGH_POP_PING_THRESHOLD` (default 7) config is met or exceeded by alive, non-afk players.
The check currently includes things like admins in test mobs or players in control of monsters. If instead only personnel on the manifest should be considered, please comment & I'll see what's possible in that regard.
Allows people to be notified for populated rounds thus incentivizing people to join for those rounds.
N/A
Tests 2 to 5 skipped due to difficulty testing without a local mock of TGS et cetera which I can't be bothered to set up
N/A
:cl:
add: You can now be pinged if there are people in the round!
/:cl:
> Add: Ping on Discord if player number meets or exceeds a new config value

- code/controllers/configuration/entries/general.dm
- code/controllers/subsystem/discord.dm
- code/modules/discord/tgs_commands.dm
- config/example/config.txt
Expands the high pop queue thingy with the ability to sign up to be pinged on Discord as well pinging the role configured.
The weight of the individuals queued on Discord can be adjusted via a config entry.
More pop more good~!
N/A
N/A
:cl:
add: You can now use !tgs highpopqueue on Discord to queue for a ping and count toward the high pop threshold!
/:cl:
> Add: Expansion to the HighPopQueue, now accepts Discord queuers

- code/modules/buildmode/submodes/proccall.dm
There's an admin tool called buildmode, which has a mode called proccall, and if you click on something without first defining a proc, you will get a white window on your client until you close it. You cannot close the white window. You just have to exit Dream Seeker.
This PR fixes that.
The root cause was that someone was calling tgui_alert without enough arguments. I just made it a regular alert.
If admins don't have to deal with jank like this then maybe they might be more merciful on the playerbase since they'll be less frustrated
:cl:
fix: Buildmode Proc-call no longer whitescreens when clicking without a set proc
/:cl:
> Fixes whitescreen on Buildmode Proccall
